[tool.poetry]
name = "ptera"
version = "0.2.1"
description = "Call graph addressing library."
authors = ["Olivier Breuleux <breuleux@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/breuleux/ptera"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pytest = "^5.3.2"
pytest-cov = "^2.8.1"
isort = {extras = ["pyproject"], version = "^4.3.21"}
flake8 = "^3.7.9"
unimport = "^0.2.0"
coverage = {extras = ["toml"], version = "^5.0.3"}
toml = "^0.10.0"
pyyaml = "^5.3"

[tool.black]
line-length = 80

[tool.isort]
known_first_party = "ptera"
known_third_party = "numpy,torch,torchvision"
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true

[tool.unimport]
exclude = ["__init__.py", "test_tools.py"]

[tool.coverage.run]
omit = []

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
